version: "3.9"
services:
  konan_db:
    image: pgvector/pgvector:pg16
    container_name: konan_db
    environment:
      POSTGRES_DB: konan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d konan_db"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - konan_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
volumes:
  konan_data:
